repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '\.(eml|mbox)$'
      - id: trailing-whitespace
        exclude: '\.(eml|mbox)$'

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        exclude: ^test/data/

  - repo: https://github.com/PyCQA/isort
    rev: 5.9.1
    hooks:
      - id: isort

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-builtins
          - flake8-unused-arguments
